# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e82323571d38707688a245eb3dca6321dd2473d8b2821ee80f70e85e8c8af79defd7623b86af785ef19bb25907d1367b57919cc8c9ae28930abb90645fca6d01

test:
  secret_key_base: c4512b35629fa5e51121eaf2dc9f1b98fabf3bf97a3200b609beb0703f3f647c37ff1ff1996716c02d53708e9757433ffef941a47492cad190daf0c6d8afca7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
